title: Manuel's Portfolio
description: Manuel's Portfolio
theme: just-the-docs

url: https://aboutmanuel.github.io/portfolio/

permalink: pretty


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/Avatar_Gr.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/Avatar_Gr.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  
# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
 
# For copy button on code
enable_copy_code_button: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false


